#include "OUTPUT_MODULE_LIST.h"
OUTPUT_MODULE_LIST::OUTPUT_MODULE_LIST() {
}

OUTPUT_MODULE_LIST::OUTPUT_MODULE_LIST(LIST&& list){
	List = list;
}

OUTPUT_MODULE_LIST::~OUTPUT_MODULE_LIST() {
}